---
default_language_version:
  python: python3.8
repos:
  - repo: git@github.com:humitos/mirrors-autoflake.git
    rev: v1.3
    hooks:
      - id: autoflake
        args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variables']
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.4.4
    hooks:
      - id: pyupgrade
        args: ['--py36-plus']
  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.2
    hooks:
      - id: flake8
        args: ['--config=.flake8']
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.770
    hooks:
      - id: mypy
