{
 "title": "Bitcoin Cash Node",
 "description": "Monitor your Bitcoin core node and aspects of the network.",
 "tags": [ "bitcoin" ],
 "time": { "from": "2021-04-18T07:03:51.043Z", "to": "2021-05-07T07:21:01.367Z" },
 "templating": {
  "list": [
   {
    "name": "coin",
    "label": "Coin",
    "query": {
     "query": "label_values(bitcoin_info, coin)"
    }
   },
   {
    "name": "chain",
    "label": "Chain",
    "query": {
     "query": "label_values(bitcoin_info{coin=\"$coin\"}, chain)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(bitcoin_info{coin=\"$coin\", chain=\"$chain\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Mempool",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes", "label": "Size" }
   ],
   "targets": [
    {
     "expr": "bitcoin_mempool_usage{instance=\"$node\"}",
     "legendFormat": "bytes"
    },
    {
     "expr": "bitcoin_mempool_bytes{instance=\"$node\"}",
     "legendFormat": "serialized-bytes"
    },
    {
     "expr": "bitcoin_mempool_size{instance=\"$node\"}",
     "legendFormat": "tx-count"
    },
    {
     "expr": "bitcoin_dsproof_count{instance=\"$node\"}",
     "legendFormat": "dsproof-count"
    }
   ]
  },
  {
   "title": "TX Stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "rate(bitcoin_txcount{instance=\"$node\"}[6h])",
     "legendFormat": "6 hours"
    },
    {
     "expr": "rate(bitcoin_txcount{instance=\"$node\"}[1d])",
     "legendFormat": "1 day"
    },
    {
     "expr": "rate(bitcoin_txcount{instance=\"$node\"}[7d])",
     "legendFormat": "7 days"
    },
    {
     "expr": "rate(bitcoin_txcount{instance=\"$node\"}[30d])",
     "legendFormat": "30 days"
    },
    {
     "expr": "bitcoin_txcount{instance=\"$node\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Last Block",
   "type": "graph",
   "description": "Size of latest block",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "bitcoin_latest_block_size{instance=\"$node\"}",
     "legendFormat": "last-block-size"
    },
    {
     "expr": "bitcoin_latest_block_txs{instance=\"$node\"}",
     "legendFormat": "last-block-txs"
    }
   ]
  },
  {
   "title": "Block Creation Rate",
   "type": "graph",
   "description": "Number of blocks created per day using different trailing rates.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(bitcoin_blocks{instance=\"$node\"}[1d]) * 86400",
     "legendFormat": "1d"
    },
    {
     "expr": "rate(bitcoin_blocks{instance=\"$node\"}[2d]) * 86400",
     "legendFormat": "2d"
    },
    {
     "expr": "rate(bitcoin_blocks{instance=\"$node\"}[4d]) * 86400",
     "legendFormat": "4d"
    },
    {
     "expr": "rate(bitcoin_blocks{instance=\"$node\"}[7d]) * 86400",
     "legendFormat": "7d"
    },
    { "expr": "144", "legendFormat": "Target" }
   ]
  },
  {
   "title": "Network Hash Rate",
   "type": "graph",
   "description": "Estimated network hashes per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "Hs" }
   ],
   "targets": [
    {
     "expr": "avg(bitcoin_hashps{instance=\"$node\"})",
     "legendFormat": "120-blocks"
    }
   ]
  },
  {
   "title": "Block value",
   "type": "graph",
   "description": "Value of the block transactions in BTC.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bitcoin_latest_block_value{instance=\"$node\"})",
     "legendFormat": "BCH"
    }
   ]
  },
  {
   "title": "Difficulty",
   "type": "graph",
   "description": "Difficulty value",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(bitcoin_difficulty{instance=\"$node\"})",
     "legendFormat": "difficulty"
    }
   ]
  },
  {
   "title": "Network traffic",
   "type": "graph",
   "description": "Sent and received traffic rates",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(bitcoin_total_bytes_sent{instance=\"$node\"}[5m]))",
     "legendFormat": "sent"
    },
    {
     "expr": "-sum(irate(bitcoin_total_bytes_recv{instance=\"$node\"}[5m]))",
     "legendFormat": "received"
    }
   ]
  },
  {
   "title": "Size on disk",
   "type": "graph",
   "description": "Estimated size of the block and undo files",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "bitcoin_size_on_disk{instance=\"$node\"}",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "graph",
   "description": "Number of peers that have been banned and the reason for the ban.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count(bitcoin_banned_until{instance=\"$node\"}) by (reason)",
     "legendFormat": "ban - {{ reason }}"
    },
    {
     "expr": "sum(bitcoin_peers{instance=\"$node\"})",
     "legendFormat": "peers"
    }
   ]
  },
  {
   "title": "Chain Branches",
   "type": "graph",
   "description": "Number of tips seen in the chain.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(bitcoin_num_chaintips{instance=\"$node\"})",
     "legendFormat": "tips"
    }
   ]
  },
  {
   "title": "RPC Info",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bitcoin_rpc_active{instance=\"$node\"}",
     "legendFormat": "Active calls"
    }
   ]
  },
  {
   "title": "DSProofs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bitcoin_dsproof_count{instance=\"$node\"}",
     "legendFormat": "Count"
    }
   ]
  }
 ]
}